## Estadística Aplicada

Sesión 2 - 11 agosto

Oscar Gabriel Martínez Rodríguez 1962702 Grupo 43

In [1]:
7>5

True

In [2]:
7>10

False

In [3]:
7>10 & 7>5

False

## Lista
Una lista en Python es una colección de objetos (mismo tipo o distinto tipo)

NombreLista = [objeto1,
                objeto2,
                objeto3,
                etc]

In [5]:
alumno1 = ['Oscar',
           'Martinez',
           17]

In [6]:
type(alumno1)

list

In [15]:
estadistica_g43 = ['Oscar',
                   'Felipe',
                   'Derek',
                   'Emmanuel']

In [16]:
estadistica_g43

['Oscar', 'Felipe', 'Derek', 'Emmanuel']

In [17]:
#Elegir a Felipe
estadistica_g43[1]

'Felipe'

In [18]:
#Elegir a Emmanuel
estadistica_g43[3]

'Emmanuel'

In [19]:
#eliminar a alguien de la lista
estadistica_g43.remove('Derek')
estadistica_g43

['Oscar', 'Felipe', 'Emmanuel']

In [20]:
#alguien se une
estadistica_g43.append('Ramirez')
estadistica_g43

['Oscar', 'Felipe', 'Emmanuel', 'Ramirez']

In [22]:
yo_enFCFM = ['Oscar',
             'LA',
             7,
             97.4]

yo_enFCFM

['Oscar', 'LA', 7, 97.4]

In [23]:
mi_carrera = yo_enFCFM[1]
mi_promedio = yo_enFCFM[3]

In [26]:
print('yo estudio en', mi_carrera, ', tengo un promedio de', mi_promedio)

yo estudio en LA , tengo un promedio de 97.4


## Librerías / Paquetes / Modulos

Una librería en Python es un conjunto de códigos que le indican a Python cómo hacer determinadas cosas

Para poder usar una librería:
1ro.  Instalarla (una vez)
2do.  Decirle a Python que la use

In [1]:
# instalar una librería de yahoo finance
!pip install yfinance


[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
#importar yahoo finance como yahoo
import yfinance as yahoo

In [4]:
yahoo.download('AAPL')

[*********************100%***********************]  1 of 1 completed


Open        High         Low       Close   Adj Close  \
Date                                                                     
1980-12-12    0.128348    0.128906    0.128348    0.128348    0.099584   
1980-12-15    0.122210    0.122210    0.121652    0.121652    0.094388   
1980-12-16    0.113281    0.113281    0.112723    0.112723    0.087461   
1980-12-17    0.115513    0.116071    0.115513    0.115513    0.089625   
1980-12-18    0.118862    0.119420    0.118862    0.118862    0.092224   
...                ...         ...         ...         ...         ...   
2023-08-07  182.130005  183.130005  177.350006  178.850006  178.850006   
2023-08-08  179.690002  180.270004  177.580002  179.800003  179.800003   
2023-08-09  180.869995  180.929993  177.009995  178.190002  178.190002   
2023-08-10  179.479996  180.750000  177.600006  177.970001  177.970001   
2023-08-11  177.320007  178.619995  176.550003  177.789993  177.789993   

               Volume  
Date                   
1980-12-12  469033600  
1980-12-15  175884800  
1980-12-16  105728000  
1980-12-17   86441600  
1980-12-18   73449600  
...               ...  
2023-08-07   97576100  
2023-08-08   67823000  
2023-08-09   60378500  
2023-08-10   54686900  
2023-08-11   51857468  

[10756 rows x 6 columns]

## Numpy

La estructura básica de numpy son los arreglos(arrays).  Un arreglo es una colección de objetos del mismo tipo

Vamos a suponer que sabemos cuántas botellas de agua vende la cafetería.  Lunes 28, martes 33, miércoles 44, jueves 40, viernes 31

In [11]:
ventas = [28,33,44,40,31]

In [12]:
type(ventas)

list

In [13]:
import numpy as np

In [14]:
ventas = np.array(ventas)
type(ventas)

numpy.ndarray

In [15]:
#sumar
np.sum(ventas)

176

In [16]:
print(f'las ventas totales de la semana son {np.sum(ventas)}')

las ventas totales de la semana son 176


In [17]:
#multiplicar
np.prod(ventas)

50413440

In [18]:
#valor máximo de un arreglo
np.max(ventas)

44

In [19]:
#valor mínimo
np.min(ventas)

28

In [21]:
#ordenar menor a mayor
np.sort(ventas)

array([28, 31, 33, 40, 44])

In [22]:
#media
np.mean(ventas)

35.2

In [25]:
#varianza poblacional
np.var(ventas)

34.959999999999994

In [27]:
#desviación estandar poblacional
np.std(ventas)

5.912698199637792

In [26]:
#varianza muestral
np.var(ventas, ddof=1)

43.699999999999996

In [28]:
#desviacion estandar muestral
np.std(ventas, ddof=1)

6.6105975524153635

In [30]:
#vector
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
np.arange(0,100, 15)

array([ 0, 15, 30, 45, 60, 75, 90])

In [36]:
np.random.seed(12)
aleatorios = np.random.randint(0,15,10)

In [37]:
aleatorios

array([11, 11,  6, 13,  1,  2,  3,  3, 12,  0])

In [40]:
aleatorios = np.sort(aleatorios)
aleatorios

array([ 0,  1,  2,  3,  3,  6, 11, 11, 12, 13])

In [41]:
#vector de zero
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [43]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [45]:
np.full(7,6)

array([6, 6, 6, 6, 6, 6, 6])

¿Cuántos minutos hay en un mes?

In [47]:
listamin = [30, 24, 60]
listamin = np.array(listamin)
np.prod(listamin)

43200

# función vs método

In [48]:
numeros = [1.4567, 4.568, 10.375]

1. Arreglo
2. Calcular la media
3. Redondear a dos decimales

In [51]:
#funcion
round(np.mean(np.array(numeros)),2)

5.47

In [54]:
#metodo
np.array(numeros).mean().round(2)

5.47